const SECOND_TO_MS = 1000;
const MINUTE_TO_MS = 60 * SECOND_TO_MS;
const HOUR_TO_MS = 60 * MINUTE_TO_MS;
const DAY_TO_MS = 24 * HOUR_TO_MS;
const WEEK_TO_MS = 7 * DAY_TO_MS;
const MONTH_TO_MS = 30 * DAY_TO_MS;
const YEAR_TO_MS = 365 * DAY_TO_MS;

export { SECOND_TO_MS, MINUTE_TO_MS, HOUR_TO_MS, DAY_TO_MS, WEEK_TO_MS, MONTH_TO_MS, YEAR_TO_MS };
