module.exports = {
  basePureUrl: process.env.BASE_PURE_URL,
  baseUrl: process.env.BASE_URL,
  domainName: process.env.DOMAIN_NAME,
  host: process.env.HOST,
  port: process.env.PORT,
  fileUrl: process.env.FILE_URL,
  fileCategoriesUrl: process.env.FILE_CATEGORIES_URL,
  stripePublicKey: process.env.STRIPE_PUBLIC_KEY,
  paypalSecretKey: process.env.PAYPAL_SECRET_KEY,
  paypalClientId: process.env.PAYPAL_CLIENT_ID,
  woosmapPublicKey: process.env.WOOSMAP_PUBLIC_KEY,
  idealPostcodesAutocompleteUrl: process.env.IDEAL_POSTCODES_AUTOCOMPLETE_URL,
  idealPostcodesKey: process.env.IDEAL_POSTCODES_KEY,
  trustpilotTemplateId: process.env.TRUSTPILOT_TEMPLATE_ID,
  stripeTimeoutPayT: process.env.STRIPE_TIMEOUT_PAYT,
  AWIN_URL: process.env.AWIN_URL,
  AWIN_ID: process.env.AWIN_ID,
  DWIN_URL: process.env.DWIN_URL,
  sessionTokenField: process.env.SESSION_TOKEN_FIELD,
  imgCDN: process.env.IMG_CDN,
  addressSuggestionsOptimization: process.env.ADDRESS_SUGGESTIONS_OPTIMIZATION,
  sessionCookieDomain: process.env.SESSION_COOKIE_DOMAIN,
  ABTesting: process.env.AB_TESTING,
  ACTesting: process.env.AC_TESTING,
  checkoutComPublicKey: process.env.CHECKOUT_COM_PUBLIC_KEY,
  checkoutComEnviroment: process.env.CHECKOUT_COM_ENVIROMENT
};
